title: Jochrisse
logo: docs/assets/Messenger_creation_511377DE-DF9D-4B6B-88F0-162F3D397DE3[1].jpeg
description: Data Anallyst| Cyber Security| Outdoor Enthusiast
show_downloads: true
theme: jekyll-theme-minimal
